# Generated by Django 3.0.6 on 2020-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('mobileno', models.CharField(max_length=10)),
            ],
        ),
    ]
