# Generated by Django 3.0.6 on 2020-05-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=64)),
                ('price', models.CharField(default=1, max_length=64)),
                ('weight', models.CharField(default=1, max_length=64)),
                ('weightunit', models.CharField(default=1, max_length=64)),
                ('description', models.CharField(default=1, max_length=64)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groceryapp.Category')),
            ],
        ),
    ]
