# Generated by Django 3.0.6 on 2020-05-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=1, max_length=64)),
                ('item_price', models.CharField(default=1, max_length=64)),
                ('name', models.CharField(default=1, max_length=64)),
                ('mobile', models.CharField(default=1, max_length=64)),
                ('houseNo', models.CharField(default=1, max_length=64)),
                ('street', models.CharField(default=1, max_length=64)),
            ],
        ),
    ]
