# Generated by Django 3.1 on 2020-08-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0008_auto_20200825_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
