# Generated by Django 3.1 on 2020-08-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0009_auto_20200825_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
        ),
    ]
