# Generated by Django 3.1 on 2020-08-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0012_auto_20200825_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdone',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groceryapp.user'),
        ),
    ]
