# Generated by Django 3.1 on 2020-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0013_orderdone_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdone',
            name='session_name',
            field=models.CharField(default=1, max_length=64),
        ),
    ]
